apiVersion: v2
appVersion: 1.0.0
description: locationcode tool - suggests airport code locations from lat/long coordinates
name: locationcode
version: 1.0.2
kubeVersion: ">=1.16.0-0"
keywords:
  - iata
maintainers:
  - name: abh
    email: ask@develooper.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Update chart build process
